// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ7W7hRwwxC-t6sLAEwGbM21G21p3AD5k',
    appId: '1:474432299061:web:87bd5b4a8da3c77166117c',
    messagingSenderId: '474432299061',
    projectId: 'fir-auth-f82fd',
    authDomain: 'fir-auth-f82fd.firebaseapp.com',
    storageBucket: 'fir-auth-f82fd.firebasestorage.app',
    measurementId: 'G-R0Y9QW15WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoxMiQLeP5Ju1u2Dvsg1pkXDcwjuEnOoQ',
    appId: '1:474432299061:android:0877b9e316638a5366117c',
    messagingSenderId: '474432299061',
    projectId: 'fir-auth-f82fd',
    storageBucket: 'fir-auth-f82fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARGfkp1Cs4fevim1FX6ybm_ATCswGxKZw',
    appId: '1:474432299061:ios:d7cb9055b6c302bf66117c',
    messagingSenderId: '474432299061',
    projectId: 'fir-auth-f82fd',
    storageBucket: 'fir-auth-f82fd.firebasestorage.app',
    androidClientId:
        '474432299061-gbsn4r4m6lgshoag4pe0gri2h9qsilom.apps.googleusercontent.com',
    iosClientId:
        '474432299061-u3lqngoimgq6tv0thno5hou6jip4j0bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkiyoReciever',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARGfkp1Cs4fevim1FX6ybm_ATCswGxKZw',
    appId: '1:474432299061:ios:d7cb9055b6c302bf66117c',
    messagingSenderId: '474432299061',
    projectId: 'fir-auth-f82fd',
    storageBucket: 'fir-auth-f82fd.firebasestorage.app',
    androidClientId:
        '474432299061-gbsn4r4m6lgshoag4pe0gri2h9qsilom.apps.googleusercontent.com',
    iosClientId:
        '474432299061-u3lqngoimgq6tv0thno5hou6jip4j0bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkiyoReciever',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ7W7hRwwxC-t6sLAEwGbM21G21p3AD5k',
    appId: '1:474432299061:web:3d882f424205a89766117c',
    messagingSenderId: '474432299061',
    projectId: 'fir-auth-f82fd',
    authDomain: 'fir-auth-f82fd.firebaseapp.com',
    storageBucket: 'fir-auth-f82fd.firebasestorage.app',
    measurementId: 'G-SXCZXYHVNB',
  );
}
