// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoxMiQLeP5Ju1u2Dvsg1pkXDcwjuEnOoQ',
    appId: '1:474432299061:android:fc65cfa8f871f45666117c',
    messagingSenderId: '474432299061',
    projectId: 'fir-auth-f82fd',
    storageBucket: 'fir-auth-f82fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARGfkp1Cs4fevim1FX6ybm_ATCswGxKZw',
    appId: '1:474432299061:ios:4c9202c2cd0ebc5666117c',
    messagingSenderId: '474432299061',
    projectId: 'fir-auth-f82fd',
    storageBucket: 'fir-auth-f82fd.firebasestorage.app',
    androidClientId:
        '474432299061-gbsn4r4m6lgshoag4pe0gri2h9qsilom.apps.googleusercontent.com',
    iosClientId:
        '474432299061-q1nd2fe1s28cc9ruvqm9pis7frksq5rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkiyoCaller',
  );
}
